FROM php:8.1-apache

COPY ./ /var/www/html/

EXPOSE 80

RUN docker-php-ext-install pdo_mysql

RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 744 /var/www/html
RUN find /var/www/html -type d -exec chmod g+s {} \;